---
title: Janne visar vägen
author: Ghost writer
date: '2022-02-01'
slug: janne-visar-vagen
categories: []
tags: []
---

Äntligen har startskottet för Vårcupen avfyrats! Trots stort manfall på grund av den grasserande pandemin fylldes pouleprotokollen med inte mindre än 13 adrenalinstinna fäktare. Särskilt roligt var att se Louise Ulltjärns tävlingsdebut!

Alla gick in med frenesi i första omgången och ingen mer än Ian som kom ut som 1:a rankad, följd av Janne och efter honom Tor. Dessa tre fäktare fick som tack för sin prestation i första pouleomgången stå över första matchen i direktutslagnigen.

I kvartsfinalen fäktades flera tuffa matcher. CH blev hårt pressad av Louise men kunde slutligen slinka förbi till semifinal med en 15-12 seger. Ian, som blivit kall av att stå över i den första matchen fick möta en glödhet Elvira som i sin tidigre match besegrat Hugo. När hon väl fått upp tävlingsångan visade sig Elvira vara svårstoppad vilket Ian bittert fick erfara.

I semifinalen ställdes Elvira mot CH och Janne mot Tor och denna gång visade sig rutinen väga tyngst vilket innebar en final mellan de båda ärrade krigarna CH och Janne. De drabbade samman med den beslutsamma iver som endast de två kan uppbringa. Några minuter senare skar CH:s vrål av besvikelse genom fäktsalen och en överlycklig Janne kunde tacka för segermatchen.

Tor kunde också belåtet notera en seger i matchen om tredjeplatsen där han ställts emot Elvira.

Här har ni den slutliga placeringslistan.
